Test GitHub Actions projet Siren V19

diff --git a/.github/workflows/siren_actions.yml b/.github/workflows/siren_actions.yml
--- a/.github/workflows/siren_actions.yml
+++ b/.github/workflows/siren_actions.yml
@@ -31,6 +31,13 @@ jobs:
           --health-timeout 5s
           --health-retries 5
     steps:
+      - name: Validate Secrets
+        run: |
+          if [ -z "${{ secrets.POSTGRES_PASSWORD }}" ]; then
+            echo "Error: POSTGRES_PASSWORD is not set."
+            exit 1
+          fi
+      # Optionally, check other secrets similarly.
       - uses: actions/checkout@v4
       - name: Set up Python
         uses: actions/setup-python@v4
